### ISSUE TITLE
Floating label animates to new position after multiline resizing

### ISSUE THREAD

**Issue by vabruzzo** [scienceai/paper-textarea#1]
Hi,

I noticed that the floating label animates itself to a new position after a textarea resize. I'm not sure if this is intended behavior or not, but it looks a bit strange when the textarea is resized due to word wrapping or a carriage return (or the removal of a line). I'd be happy to take a closer look at the code if this is an issue.

**Comment by callahanchris** [comment]
Thanks for filing this, it is definitely a bug. Will push the new fix asap.
